---
- hosts: all
  become: true
  tasks:
  - name: Install yum utils
    yum:
      name: yum-utils
      state: latest
    when: ansible_facts['os_family'] == 'RedHat'

  - name: Install device-mapper-persistent-data
    yum:
      name: device-mapper-persistent-data
      state: latest
    when: ansible_facts['os_family'] == 'RedHat'

  - name: Install lvm2
    yum:
      name: lvm2
      state: latest
    when: ansible_facts['os_family'] == 'RedHat'

  - name: Add Docker repo
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docer-ce.repo
    become: yes
    when: ansible_facts['os_family'] == 'RedHat'

  - name: Enable Docker Edge repo
    ini_file:
      dest: /etc/yum.repos.d/docer-ce.repo
      section: 'docker-ce-edge'
      option: enabled
      value: 0
    become: yes
    when: ansible_facts['os_family'] == 'RedHat'

  - name: Enable Docker Test repo
    ini_file:
      dest: /etc/yum.repos.d/docer-ce.repo
      section: 'docker-ce-test'
      option: enabled
      value: 0
    become: yes
    when: ansible_facts['os_family'] == 'RedHat'

  - name: Update the apt package index
    become: yes
    apt:
      name: "*"
      state: latest
      update_cache: yes
      force_apt_get: yes
    when: ansible_facts['os_family'] == "Debian"

  - name: Install packages for apt add repository over HTTPS
    become: yes
    apt:
      name: "{{ packagesdep }}"
      force_apt_get: yes
      state: latest
      update_cache: yes
    vars:
      packagesdep:
      - git
      - apt-transport-https
      - ca-certificates
      - wget
      - software-properties-common
      - gnupg2
      - curl
    when: ansible_facts['os_family'] == "Debian"

  - name: Add Apt signing key from official docker repo
    apt_key:
      url: https://download.docker.com/linux/debian/gpg
      state: present
    when: ansible_facts['os_family'] == "Debian"

  - name: add docker official repository for Debian Stretch
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
      state: present
    when: ansible_facts['os_family'] == "Debian"

  - name: Index new repo into the cache
    become: yes
    apt:
      name: "*"
      state: latest
      update_cache: yes
      force_apt_get: yes
    when: ansible_facts['os_family'] == "Debian"

  - name: actually install docker
    apt:
      name: "docker-ce"
      state: latest

  - name: create folder
    file:
      path: /TPDocker
      state: directory
      mode: '0755'

  - name: copier les sources des projets result
    copy: 
      src: result 
      dest: /TPDocker/
    
  - name: copier les sources des projets vote 
    copy:
      src: vote  
      dest: /TPDocker/

  - name: copier les sources des projets worker
    copy:
      src: worker
      dest: /TPDocker/

  - name: build docker
    service:
      name: docker
      state: started
      enabled: yes

  - name: build l'image result
    command: docker build -t image_result /TPDocker/result 

  - name: build l'image vote
    command: docker build -t image_vote /TPDocker/vote

  - name: build l'image worker
    command: docker build -t image_worker /TPDocker/worker  

  - name: Suppresion des sources
    file:
      state: absent
      path: ./TPDocker
  